# Generated by Django 3.0.3 on 2020-04-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme_image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=''),
        ),
    ]
