# Generated by Django 3.0.3 on 2020-04-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200331_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
