# Generated by Django 3.0.3 on 2020-04-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200402_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
