# Generated by Django 3.0.3 on 2020-02-21 21:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200221_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 21, 55, 6, 342280, tzinfo=utc)),
        ),
    ]
