# Generated by Django 3.0.3 on 2020-02-22 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200221_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='git_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 8, 46, 10, 316109, tzinfo=utc)),
        ),
    ]
