# Generated by Django 3.0.3 on 2020-02-24 06:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200223_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 6, 18, 37, 290422, tzinfo=utc)),
        ),
    ]
