# Generated by Django 3.0.3 on 2020-02-25 04:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200224_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 4, 38, 1, 152641, tzinfo=utc)),
        ),
    ]
