# Generated by Django 3.0.3 on 2020-02-25 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200225_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 19, 22, 52, 821137, tzinfo=utc)),
        ),
    ]
