# Generated by Django 3.0.3 on 2020-02-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200227_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Yakov'),
            preserve_default=False,
        ),
    ]
