# Generated by Django 3.0.3 on 2020-03-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_topicofpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('General', 'General'), ('Sports & Fitness', 'Sports & Fitness'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Music', 'Music'), ('Education', 'Education'), ('Science & Tech', 'Science & Tech'), ('Humor', 'Humor'), ('Food & Drink', 'Food & Drink'), ('Family & Parenting', 'Family & Parenting'), ('Style', 'Style'), ('Arts', 'Arts'), ('Travel', 'Travel'), ('Animals', 'Animals')], default='General', max_length=30),
        ),
    ]
