# Generated by Django 3.0.3 on 2020-03-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200330_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Arts', 'Arts'), ('Travel', 'Travel')], default='General', max_length=30),
        ),
    ]
